import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openIdentityStore } from './identity-store.js';
import { createServer } from './index.js';

function fixture(t) {
  const directory = mkdtempSync(join(tmpdir(), 'fly-individuals-'));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  let store = openIdentityStore(directory);
  const primaryId = store.primaryId;
  const secondId = store.createIndividual().individualId;
  const thirdId = store.createIndividual().individualId;
  store.close();
  store = openIdentityStore(directory, { residentIds: [secondId, thirdId] });
  t.after(() => store.close());
  return { store, directory, primaryId, secondId, thirdId };
}
const steps = (store, count) => { for (let i = 0; i < count; i++) store.step(); };

test('fresh identities are explicit, durable and unloaded; selected residents boot paused without a pair ceiling', t => {
  const { store, directory, primaryId, secondId, thirdId } = fixture(t);
  const ids = [primaryId, secondId, thirdId];
  const snapshots = ids.map(id => store.snapshot(id));
  assert.equal(new Set(snapshots.map(state => state.sessionId)).size, 3);
  assert.ok(snapshots.every(state => state.status === 'paused' && state.tick === 0 && state.persistence.resident));
  steps(store, 100);
  assert.deepEqual(ids.map(id => store.snapshot(id)), snapshots);
  store.control(primaryId, 'start');
  store.encounter(primaryId, 'nectar');
  steps(store, 20);
  const newIndividual = store.createIndividual();
  assert.equal(newIndividual.status, 'saved-unloaded');
  assert.equal(newIndividual.tick, 0);
  assert.equal(newIndividual.persistence.branchOf, null);
  assert.equal(newIndividual.stimulusPolicy.reservedDose, 0);
  assert.throws(() => store.control(newIndividual.individualId, 'start'), /unloaded/);
  assert.equal(store.list().length, 4);
  store.save(primaryId);
  const saved = readFileSync(join(directory, 'identities.json'), 'utf8');
  store.close();
  const reopened = openIdentityStore(directory);
  t.after(() => reopened.close());
  assert.equal(reopened.list().filter(record => record.resident).length, 1);
  assert.equal(reopened.snapshot().status, 'paused');
  assert.equal(reopened.snapshot().tick, 20);
  assert.equal(reopened.snapshot(secondId).status, 'saved-unloaded');
  assert.equal(readFileSync(join(directory, 'identities.json'), 'utf8'), saved);
});

test('interleaved saves, restores, rest and encounters preserve every other individual exactly', t => {
  const { store, directory, primaryId: a, secondId: b, thirdId: c } = fixture(t);
  store.control(a, 'start');
  store.control(b, 'start');
  store.encounter(a, 'nectar');
  store.encounter(b, 'floral');
  steps(store, 73);
  const aSaved = store.save(a);
  const bSaved = store.save(b);
  const cBefore = store.snapshot(c);
  assert.notDeepEqual(aSaved.neural, bSaved.neural);
  store.control(a, 'rest');
  assert.deepEqual(store.snapshot(b), bSaved);
  assert.deepEqual(store.snapshot(c), cBefore);
  steps(store, 21);
  const bBefore = store.snapshot(b);
  const aRestored = store.restore(a, aSaved.persistence.checkpointId);
  assert.equal(aRestored.status, 'paused');
  assert.notEqual(aRestored.sessionId, aSaved.sessionId);
  assert.deepEqual(aRestored.neural, aSaved.neural);
  assert.equal(aRestored.stimulusPolicy.reservedDose, aSaved.stimulusPolicy.reservedDose);
  assert.equal(aRestored.chemistry.some(effect => effect.active), false);
  assert.deepEqual(store.snapshot(b), bBefore);
  const aBefore = store.snapshot(a);
  store.restore(b, bSaved.persistence.checkpointId);
  assert.deepEqual(store.snapshot(a), aBefore);
  assert.deepEqual(store.snapshot(c), cBefore);
  const states = [a, b, c].map(id => store.snapshot(id));
  store.close();
  const reopened = openIdentityStore(directory, { residentIds: [b, c] });
  t.after(() => reopened.close());
  for (const [i, id] of [a, b, c].entries()) {
    assert.equal(reopened.snapshot(id).status, 'paused');
    assert.deepEqual(reopened.snapshot(id).neural, states[i].neural);
    assert.notEqual(reopened.snapshot(id).sessionId, states[i].sessionId);
  }
  steps(reopened, 100);
  assert.deepEqual([a, b, c].map(id => reopened.snapshot(id).tick), states.map(state => state.tick));
});

test('wrong-individual restore and persistence errors stop only their target and retain its durable head', t => {
  const { store, directory, primaryId: a, secondId: b, thirdId: c } = fixture(t);
  store.control(a, 'start'); store.control(b, 'start');
  steps(store, 19);
  const before = store.snapshot(b);
  const aBefore = store.snapshot(a);
  assert.throws(() => store.restore(a, before.persistence.checkpointId), /does not belong/);
  assert.equal(store.snapshot(a).status, 'fault');
  assert.deepEqual(store.snapshot(a).neural, aBefore.neural);
  assert.equal(store.snapshot(a).persistence.checkpointId, aBefore.persistence.checkpointId);
  assert.deepEqual(store.snapshot(b), before);
  store.save(b);
  assert.ok(store.snapshot(a).persistence.error);
  assert.equal(store.snapshot(b).persistence.error, null);
  steps(store, 1);
  assert.equal(store.snapshot(a).tick, 19);
  assert.equal(store.snapshot(b).tick, 20);
  store.close();
  const failing = openIdentityStore(directory, { residentIds: [b, c], write: () => { throw new Error('simulated disk full'); } });
  t.after(() => failing.close());
  failing.control(a, 'start'); failing.control(b, 'start');
  steps(failing, 1);
  const aRunning = failing.snapshot(a);
  const bRunning = failing.snapshot(b);
  const disk = readFileSync(join(directory, 'identities.json'), 'utf8');
  assert.throws(() => failing.encounter(b, 'nectar'), /disk full/);
  assert.equal(failing.snapshot(b).status, 'fault');
  assert.equal(failing.snapshot(b).stimulusPolicy.reservedDose, bRunning.stimulusPolicy.reservedDose);
  assert.deepEqual(failing.snapshot(b).neural, bRunning.neural);
  assert.deepEqual(failing.snapshot(a), aRunning);
  assert.throws(() => failing.createIndividual(), /disk full/);
  assert.equal(failing.list().length, 3);
  assert.deepEqual(failing.snapshot(a), aRunning);
  assert.equal(readFileSync(join(directory, 'identities.json'), 'utf8'), disk);
});

test('lineage and dataset metadata cannot mutate registry state; incompatible namespaces fail before activation', t => {
  const { store, directory, primaryId, secondId } = fixture(t);
  const checkpointId = store.snapshot(secondId).persistence.checkpointId;
  const replica = store.replica(secondId, checkpointId);
  replica.persistence.branchOf.individualId = primaryId;
  const listing = store.list();
  listing.find(record => record.individualId === replica.individualId).branchOf.checkpointId = randomUUID();
  listing.find(record => record.individualId === secondId).dataset.namespace = 'another-dataset';
  assert.deepEqual(store.snapshot(replica.individualId).persistence.branchOf, { individualId: secondId, checkpointId });
  assert.equal(store.snapshot(secondId).dataset.namespace, 'synthetic-fixture');
  store.close();
  const file = join(directory, 'identities.json');
  const original = readFileSync(file, 'utf8');
  const corrupted = JSON.parse(original);
  const checkpoint = corrupted.individuals.find(record => record.individualId === secondId).checkpoints[0];
  checkpoint.payload.dataset.namespace = 'other-specimen';
  checkpoint.sha256 = createHash('sha256').update(JSON.stringify(checkpoint.payload)).digest('hex');
  writeFileSync(file, JSON.stringify(corrupted));
  assert.throws(() => openIdentityStore(directory, { residentIds: [secondId] }), /incompatible/);
  assert.equal(readFileSync(file, 'utf8'), JSON.stringify(corrupted));
  writeFileSync(file, original);
  assert.throws(() => openIdentityStore(directory, { residentIds: [randomUUID()] }), /not found/);
  assert.throws(() => openIdentityStore(directory, { residentIds: [secondId, secondId] }), /unique/);
  const recovered = openIdentityStore(directory, { residentIds: [secondId] });
  t.after(() => recovered.close());
  assert.equal(recovered.snapshot(secondId).status, 'paused');
  assert.equal(readFileSync(file, 'utf8'), original);
});

test('HTTP reads never create individuals and scoped commands reject crossed IDs, sessions and duplicate creation', async t => {
  const { store, primaryId: a, secondId: b } = fixture(t);
  const server = createServer({ identities: store, autoTick: false });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const path = id => `/api/individuals/${id}`;
  const get = id => fetch(`${base}${path(id)}`).then(response => response.json());
  const post = (route, body, headers = {}) => fetch(`${base}${route}`, { method: 'POST',
    headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(body) });
  const envelope = (state, extra = {}) => ({ protocolVersion: 1, individualId: state.individualId,
    sessionId: state.sessionId, sequence: state.commandSequence + 1, ...extra });
  const initial = await get(a);
  const bInitial = await get(b);
  assert.deepEqual(await Promise.all([get(a), get(a)]), [initial, initial]);
  assert.equal(store.list().length, 3);
  assert.equal((await post(`${path(b)}/control`, envelope(initial, { action: 'start' }))).status, 409);
  assert.equal((await post(`${path(b)}/control`, envelope(bInitial, { sessionId: initial.sessionId, action: 'start' }))).status, 409);
  assert.deepEqual(await get(b), bInitial);
  assert.equal((await post(`${path(b)}/control`, envelope(bInitial, { action: 'start' }))).status, 200);
  store.step();
  const bRunning = await get(b);
  assert.equal(bRunning.tick, 1);
  assert.deepEqual(await get(a), initial);
  assert.equal((await post(`${path(b)}/encounters`, envelope(bRunning, { compoundId: 'floral' }))).status, 200);
  const bSaved = await get(b);
  const restored = await (await post(`${path(b)}/restore`, envelope(bSaved, { checkpointId: bSaved.persistence.checkpointId }))).json();
  assert.equal(restored.status, 'paused');
  assert.equal((await post(`${path(b)}/control`, envelope(restored, { sessionId: bSaved.sessionId, action: 'start' }))).status, 409);
  assert.deepEqual(await get(a), initial);
  assert.equal((await post('/api/individuals', envelope(initial), { Origin: 'https://other.example' })).status, 403);
  assert.equal((await post('/api/individuals', envelope(initial, { resident: true }))).status, 409);
  const created = await (await post('/api/individuals', envelope(initial))).json();
  assert.equal(created.status, 'saved-unloaded');
  assert.equal(created.commandSequence, 0);
  assert.equal(created.persistence.branchOf, null);
  assert.equal((await post('/api/individuals', envelope(initial))).status, 409);
  assert.equal(store.list().length, 4);
  assert.equal((await post(`${path(created.individualId)}/control`, envelope(created, { action: 'start' }))).status, 409);
  assert.equal((await get(a)).commandSequence, 1);
  assert.deepEqual(await get(b), restored);
});
