import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openIdentityStore } from './identity-store.js';
import { createSharedHttp } from './shared-http.js';
async function setup(t) {
  const directory = mkdtempSync(join(tmpdir(), 'shared-http-')), identities = openIdentityStore(directory);
  const ids = [identities.primaryId, identities.create().individualId]; identities.load(ids[1]);
  const sequences = new Map(), transitions = [], frames = [];
  const snapshot = id => ({ ...identities.snapshot(id), commandSequence: sequences.get(id) ?? 0 });
  const handler = createSharedHttp({ identities, snapshot, sequenceFor: id => sequences.get(id) ?? 0,
    consumeSequences: members => members.forEach(item => sequences.set(item.individualId, item.sequence)),
    afterTransition: (...args) => transitions.push(args), afterFrames: traces => frames.push(traces) });
  const server = createServer(async (req, res) => { if (!await handler(req, res, new URL(req.url, 'http://localhost'))) { res.writeHead(404); res.end(); } });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise(resolve => server.close(resolve)); identities.close(); rmSync(directory, { recursive: true }); });
  const request = async (path, body) => { const response = await fetch(`http://127.0.0.1:${server.address().port}/api/shared/${path}`, body === undefined ? {} : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); return { status: response.status, value: await response.json() }; };
  const members = () => ids.map(id => { const s = snapshot(id); return { protocolVersion: 1, individualId: id, sessionId: s.sessionId, sequence: s.commandSequence + 1 }; });
  const control = (shared, action) => request(`${shared.sharedId}/control`, { protocolVersion: 1, sharedId: shared.sharedId, worldEpoch: shared.worldEpoch, sequence: shared.commandSequence + 1, action });
  return { identities, ids, snapshot, request, members, control, transitions, frames };
}
test('shared HTTP preserves existing runtimes across join, atomic frames, joint save and paused restore', async t => {
  const f = await setup(t), initial = f.ids.map(f.snapshot);
  let result = await f.request('join', { protocolVersion: 1, members: f.members() });
  assert.equal(result.status, 200); const token = result.value.controllerToken; let shared = result.value.shared;
  assert.equal(shared.status, 'paused'); assert.deepEqual(result.value.members.map(s => s.sessionId), initial.map(s => s.sessionId));
  assert.equal(JSON.stringify((await f.request(shared.sharedId)).value).includes(token), false);
  shared = (await f.control(shared, 'start')).value.shared;
  const frame = { controllerToken: token, worldEpoch: shared.worldEpoch, worldTick: shared.tick, frames: shared.participants.map((p,i) => ({ version: 1, individualId: p.individualId, sessionId: p.sessionId, environmentEpoch: shared.worldEpoch, frameId: shared.tick, simTimeMs: p.simTimeMs, capturedAtMs: Date.now(), camera: 'controller', width: 8, height: 4, rgb: Array(96).fill(i * 255) })) };
  const before = f.ids.map(f.snapshot);
  assert.equal((await f.request(`${shared.sharedId}/frames`, { ...frame, frames: frame.frames.slice(1) })).status, 409);
  assert.deepEqual(f.ids.map(f.snapshot), before);
  result = await f.request(`${shared.sharedId}/frames`, frame); assert.equal(result.status, 200); shared = result.value.shared;
  assert.equal(shared.tick, 1); assert.equal(f.frames.length, 1); assert.notDeepEqual(result.value.members[0].neural, result.value.members[1].neural);
  const saved = (await f.control(shared, 'save')).value; shared = saved.shared;
  assert.equal(saved.checkpoint.payload.tick, 1);
  assert.equal((await f.request('checkpoints')).value.checkpoints.length, 1);
  await f.control(shared, 'separate');
  result = await f.request('restore', { protocolVersion: 1, jointCheckpointId: saved.checkpoint.jointCheckpointId, members: f.members() });
  assert.equal(result.status, 200); assert.equal(result.value.shared.status, 'paused'); assert.equal(result.value.shared.tick, 1);
  assert.notEqual(result.value.controllerToken, token);
  assert.notDeepEqual(result.value.members.map(s => s.sessionId), initial.map(s => s.sessionId));
  assert.deepEqual(result.value.shared.participants.map(p => p.pose), saved.shared.participants.map(p => p.pose));
  assert.deepEqual(f.transitions.map(item => item[1]), ['join', 'start', 'save', 'separate', 'restore']);
});
test('all member commands validate before consuming any; stale group and wrong lease cannot advance', async t => {
  const f = await setup(t), members = f.members(); members[1].sessionId = 'stale';
  assert.equal((await f.request('join', { protocolVersion: 1, members })).status, 409);
  assert.deepEqual(f.ids.map(id => f.snapshot(id).commandSequence), [0,0]);
  assert.equal((await f.request('join', { protocolVersion: 1, members: [f.members()[0],f.members()[0]] })).status, 400);
  const joined = (await f.request('join', { protocolVersion: 1, members: f.members() })).value;
  await f.control(joined.shared, 'start');
  assert.equal((await f.control(joined.shared, 'pause')).status, 409);
  assert.equal((await f.request(`${joined.shared.sharedId}/frames`, { controllerToken: '0'.repeat(64) })).status, 409);
  assert.deepEqual(f.ids.map(id => f.snapshot(id).tick), [0,0]);
});
test('joint restore requires exact durable members and rejects oversized, extra and query-bearing input', async t => {
  const f=await setup(t);
  const joined=(await f.request('join',{protocolVersion:1,members:f.members()})).value;
  const saved=(await f.control(joined.shared,'save')).value;
  await f.control(saved.shared,'separate');
  const third=f.identities.create().individualId;f.identities.load(third);
  const members=f.members();members[1]={protocolVersion:1,individualId:third,sessionId:f.snapshot(third).sessionId,sequence:1};
  const before=f.ids.map(f.snapshot);
  assert.equal((await f.request('restore',{protocolVersion:1,jointCheckpointId:saved.checkpoint.jointCheckpointId,members})).status,409);
  assert.deepEqual(f.ids.map(f.snapshot),before);
  assert.equal((await f.request('join',{protocolVersion:1,members:f.members(),extra:true})).status,400);
  assert.equal((await f.request('join',{padding:'x'.repeat(4096)})).status,413);
  assert.equal((await f.request('checkpoints?unexpected=true')).status,400);
});
test('app integration protects origin, invalidates both language recipients and preserves partial home capture', async t => {
  const { createServer: createApp } = await import('./index.js');
  const { createCreativeSessions } = await import('./creative-session.js');
  const directory=mkdtempSync(join(tmpdir(),'shared-app-')), identities=openIdentityStore(directory), creativeSessions=createCreativeSessions();
  const ids=[identities.primaryId,identities.create().individualId];identities.load(ids[1]);
  const revoked=[];
  const language={snapshot:()=>({available:false}),lifecycle:id=>revoked.push(id),close(){},tick:async()=>{},arm:()=>{throw new Error('Must not arm shared recipients');}};
  identities.environmentControl(ids[0],'attach');identities.control(ids[0],'start');creativeSessions.start(identities.snapshot(ids[0]));
  const app=createApp({identities,creativeSessions,languageService:language,autoTick:false});
  await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));
  t.after(async()=>{await new Promise(resolve=>app.close(resolve));rmSync(directory,{recursive:true});});
  const base=`http://127.0.0.1:${app.address().port}`;
  const post=(path,body,headers={})=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
  const states=await Promise.all(ids.map(id=>fetch(`${base}/api/individuals/${id}`).then(r=>r.json())));
  const members=states.map(s=>({protocolVersion:1,individualId:s.individualId,sessionId:s.sessionId,sequence:s.commandSequence+1}));
  assert.equal((await post('/api/shared/join',{protocolVersion:1,members},{origin:'https://untrusted.example'})).status,403);
  assert.equal(identities.snapshot(ids[0]).sharedSession,null);
  const joinedResponse=await post('/api/shared/join',{protocolVersion:1,members});assert.equal(joinedResponse.status,200);const joined=await joinedResponse.json();
  assert.deepEqual(revoked,ids);assert.equal(joined.members[0].creativeCapture.active,false);assert.equal(joined.members[0].creativeCapture.partial,true);
  assert.equal(JSON.stringify((await fetch(`${base}/api/shared/${joined.shared.sharedId}`).then(r=>r.json()))).includes(joined.controllerToken),false);
  const member=joined.members[0];
  assert.equal((await post(`/api/individuals/${ids[0]}/language`,{protocolVersion:1,individualId:ids[0],sessionId:member.sessionId,sequence:member.commandSequence+1,operation:'arm',payload:{}})).status,409);
  const shared=joined.shared;
  assert.equal((await post(`/api/shared/${shared.sharedId}/control`,{protocolVersion:1,sharedId:shared.sharedId,worldEpoch:shared.worldEpoch,sequence:1,action:'start'})).status,200);
  assert.deepEqual(revoked,[...ids,...ids]);
  for(const id of ids)assert.equal(identities.snapshot(id).tick,0);
});
